project:
  type: website

execute:
  freeze: auto

website:
  title: "Jonas Wilinski"
  site-url: https://j0nasw.github.io/
  repo-url: https://github.com/j0nasw/j0nasw.github.io
  page-navigation: false
  reader-mode: false
  search: true
  favicon: assets/icons/favicon.png
  bread-crumbs: false

  # cookie-consent:
  #   type: implied
  #   style: simple
  #   palette: light
  #   policy-url: /privacy.qmd

  twitter-card: true

  open-graph:
    locale: de_DE
    site-name: Jonas Wilinski

  navbar:
    pinned: true
    # logo: "assets/logo/logo_tie.svg"
    # logo-alt: "Jonas Wilinski"
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: research.qmd
        text: Research & Teaching
      # - href: about.qmd
      #   text: About
    right:

      - icon: envelope
        href: "{{<var website.mail>}}"
        aria-label: Drop us a Mail
      # - icon: github
      #   menu:
      #     - text: "TIE Profile"
      #       url: "{{<var author.github>}}"
      #     - text: "Source Code"
      #       url: "{{<var website.github>}}"
      #     - text: "Report a Bug"
      #       url: "{{<var website.github_bug>}}"
      # - icon: box-arrow-in-right
      #   menu:
      #     - text: "Courses"
      #       url: teaching.qmd
      #     - text: "Logos & Templates"
      #       url: resources.qmd
      # Icons can be found at https://icons.getbootstrap.com/

  sidebar:
    style: "floating"
    search: true
    contents: auto

  page-footer:
    left:
      © {{< var website.c_year >}} by [{{< var author.name >}}]({{< var author.url >}})<br>
      [Imprint](/imprint.qmd) | [Data Privacy](/privacy.qmd)
    right:
      Made with {{< var tech.quarto >}}<br>
      View the source at [GitHub]({{< var website.github >}})
    border: false
    background: light

format:
  html:
    theme:
      light:
        - "themes/jw_light.scss"
      dark: 
        - "themes/jw_dark.scss"
    toc: true
    toc-depth: 2
    toc-title: Contents
    # author: "JW"
    page-layout: full
